-- Gerado por scripts/generate-seed.ts. Não edite à mão.
begin;
truncate public.projects, public.posts, public.services, public.team_members, public.awards, public.clients restart identity;

insert into public.projects (slug, name, category, year, location, area, client, summary, description, cover, gallery, featured, sort_order) values
  ('casa-do-vale', 'Casa do Vale', 'Residencial', 2025, 'Nova Lima, MG', 480, 'Residência particular', 'Uma casa baixa e silenciosa, pousada sobre a encosta como uma linha no horizonte.', array['A Casa do Vale nasce da topografia. Em vez de vencer o declive, o projeto se acomoda a ele em dois volumes horizontais que acompanham as curvas de nível e enquadram a paisagem do vale.', 'O concreto aparente, moldado com fôrmas de tábua, conversa com a madeira natural das esquadrias e com a pedra local dos muros de arrimo. A paleta reduzida deixa que a luz e a vegetação façam o restante do trabalho.', 'As áreas sociais se abrem integralmente para o terraço através de grandes panos de vidro, enquanto os quartos se recolhem num volume mais fechado, protegido por brises verticais que filtram o sol da tarde.']::text[], '{"src":"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2000&q=80","alt":"Fachada da Casa do Vale com piscina e grandes panos de vidro","orientation":"landscape"}'::jsonb, '[{"src":"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=2000&q=80","alt":"Sala de estar integrada ao terraço","orientation":"landscape","caption":"Estar integrado ao terraço"},{"src":"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=2000&q=80","alt":"Cozinha com bancada em pedra e marcenaria em madeira","orientation":"portrait","caption":"Cozinha e bancada em pedra"},{"src":"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=2000&q=80","alt":"Detalhe de interior com luz natural","orientation":"landscape","caption":"Luz da manhã no estar íntimo"}]'::jsonb, true, 1),
  ('galeria-norte', 'Galeria Norte', 'Cultural', 2024, 'São Paulo, SP', 1250, 'Instituto Norte de Arte', 'Um espaço expositivo que trata a luz zenital como matéria de projeto.', array['Instalada num antigo galpão industrial, a Galeria Norte preserva a estrutura original de tesouras metálicas e insere, sob ela, uma sequência de salas brancas de proporções variadas.', 'Sheds reconstruídos distribuem luz natural difusa sobre as paredes expositivas, reduzindo a dependência de iluminação artificial e criando uma atmosfera que muda ao longo do dia.', 'O percurso é pensado como uma caminhada lenta: salas amplas se alternam com passagens estreitas e baixas, e cada abertura para o pátio interno funciona como pausa entre uma obra e outra.']::text[], '{"src":"https://images.unsplash.com/photo-1554907984-15263bfd63bd?auto=format&fit=crop&w=2000&q=80","alt":"Sala expositiva branca da Galeria Norte com luz natural","orientation":"landscape"}'::jsonb, '[{"src":"https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=2000&q=80","alt":"Volume externo em concreto da galeria","orientation":"portrait","caption":"Volume de acesso"},{"src":"https://images.unsplash.com/photo-1536924940846-227afb31e2a5?auto=format&fit=crop&w=2000&q=80","alt":"Interior de sala de exposição com obras","orientation":"landscape","caption":"Sala principal"},{"src":"https://images.unsplash.com/photo-1431576901776-e539bd916ba2?auto=format&fit=crop&w=2000&q=80","alt":"Detalhe da fachada em concreto","orientation":"portrait","caption":"Detalhe da fachada"}]'::jsonb, true, 2),
  ('atelier-lumen', 'Atelier Lumen', 'Interiores', 2025, 'Rio de Janeiro, RJ', 210, 'Lumen Design de Joias', 'Um interior em tons de areia onde cada peça de mobiliário foi desenhada sob medida.', array['O Atelier Lumen reúne showroom, oficina e escritório de uma marca de joias autorais. O desafio era criar um ambiente acolhedor para clientes sem esconder o trabalho artesanal que acontece ali.', 'Uma grande estante em carvalho organiza o espaço e separa as áreas sem fechá-las. Paredes em reboco de cal, piso em cimento queimado claro e linho nas cortinas compõem uma base serena, quase monocromática.']::text[], '{"src":"https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=2000&q=80","alt":"Sala do Atelier Lumen em tons de areia com mobiliário claro","orientation":"portrait"}'::jsonb, '[{"src":"https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=2000&q=80","alt":"Ambiente de descanso com roupa de cama em linho","orientation":"landscape","caption":"Sala de atendimento reservado"},{"src":"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=2000&q=80","alt":"Estar com sofá e poltronas em tons neutros","orientation":"portrait","caption":"Estar do showroom"},{"src":"https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=2000&q=80","alt":"Ambiente com luminária e mobiliário em madeira","orientation":"landscape","caption":"Mesa de trabalho"}]'::jsonb, true, 3),
  ('sede-terra', 'Sede Terra', 'Comercial', 2023, 'Curitiba, PR', 2400, 'Terra Engenharia', 'Escritórios corporativos organizados em torno de um vazio central iluminado.', array['A nova sede da Terra Engenharia foi concebida como um lugar de encontro. Os pavimentos de trabalho se distribuem ao redor de um átrio de pé direito triplo que conecta visualmente todas as equipes.', 'A estrutura em concreto e as lajes nervuradas ficam aparentes. Painéis acústicos em madeira e jardins internos equilibram a rigidez do sistema construtivo e melhoram o conforto ao longo do dia.', 'Na fachada, uma segunda pele de brises horizontais controla a insolação e dá ao edifício a sua leitura serena e repetitiva.']::text[], '{"src":"https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=2000&q=80","alt":"Área de trabalho aberta da Sede Terra com luz natural","orientation":"landscape"}'::jsonb, '[{"src":"https://images.unsplash.com/photo-1524230572899-a752b3835840?auto=format&fit=crop&w=2000&q=80","alt":"Vista do edifício em perspectiva","orientation":"portrait","caption":"Fachada com brises"},{"src":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=2000&q=80","alt":"Espaço de convivência e refeitório","orientation":"landscape","caption":"Café no térreo"},{"src":"https://images.unsplash.com/photo-1486718448742-163732cd1544?auto=format&fit=crop&w=2000&q=80","alt":"Detalhe de concreto aparente","orientation":"portrait","caption":"Laje nervurada aparente"}]'::jsonb, true, 4),
  ('casa-patio', 'Casa Pátio', 'Residencial', 2022, 'Campinas, SP', 360, 'Residência particular', 'Uma casa voltada para dentro, onde o pátio é o cômodo mais importante.', array['Num lote urbano estreito e cercado por vizinhos, a Casa Pátio escolhe olhar para dentro. Todos os ambientes se abrem para um pátio central plantado com uma única árvore.', 'Os muros externos quase cegos garantem privacidade, enquanto os caixilhos de piso a teto voltados para o pátio trazem luz e ventilação cruzada a todos os cômodos.']::text[], '{"src":"https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=2000&q=80","alt":"Fachada da Casa Pátio ao entardecer","orientation":"landscape"}'::jsonb, '[{"src":"https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=2000&q=80","alt":"Sala de estar voltada para o pátio","orientation":"landscape","caption":"Estar e pátio"},{"src":"https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=2000&q=80","alt":"Circulação interna com luz natural","orientation":"portrait","caption":"Circulação"},{"src":"https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=2000&q=80","alt":"Quarto principal com roupa de cama clara","orientation":"landscape","caption":"Quarto principal"}]'::jsonb, false, 5),
  ('pavilhao-das-aguas', 'Pavilhão das Águas', 'Cultural', 2021, 'Brumadinho, MG', 640, 'Fundação Águas Claras', 'Um pavilhão de visitação que se debruça sobre o espelho d''água.', array['Implantado à beira de um lago, o pavilhão recebe visitantes de um parque de arte e paisagem. Uma cobertura única em concreto avança sobre a água e cria uma grande sombra habitável.', 'Por baixo dela, volumes leves abrigam recepção, café e uma pequena sala de projeções. A escada escultórica conduz a um mirante que recoloca o visitante diante da paisagem.']::text[], '{"src":"https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=2000&q=80","alt":"Volume em concreto do Pavilhão das Águas","orientation":"portrait"}'::jsonb, '[{"src":"https://images.unsplash.com/photo-1503174971373-b1f69850bded?auto=format&fit=crop&w=2000&q=80","alt":"Escada escultórica em espiral","orientation":"portrait","caption":"Escada do mirante"},{"src":"https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?auto=format&fit=crop&w=2000&q=80","alt":"Fachada em concreto em preto e branco","orientation":"landscape","caption":"Cobertura em balanço"},{"src":"https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=2000&q=80","alt":"Jardim com vegetação nativa","orientation":"landscape","caption":"Paisagismo com espécies nativas"}]'::jsonb, false, 6),
  ('apartamento-jardins', 'Apartamento Jardins', 'Interiores', 2024, 'São Paulo, SP', 190, 'Residência particular', 'A reforma de um apartamento dos anos 1960 que devolve a planta à sua clareza original.', array['O projeto remove divisórias acumuladas ao longo de décadas e recupera a generosidade da planta modernista. O piso de tacos foi restaurado e as esquadrias originais, recuperadas.', 'Marcenaria em freijó e superfícies em travertino compõem uma atmosfera calorosa e atemporal, pensada para receber a coleção de arte dos moradores.']::text[], '{"src":"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=2000&q=80","alt":"Sala do Apartamento Jardins com luz natural","orientation":"landscape"}'::jsonb, '[{"src":"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=2000&q=80","alt":"Estar com sofá em tecido claro","orientation":"portrait","caption":"Estar principal"},{"src":"https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=2000&q=80","alt":"Dormitório com cabeceira em madeira","orientation":"landscape","caption":"Dormitório"},{"src":"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=2000&q=80","alt":"Sala de jantar integrada","orientation":"landscape","caption":"Jantar"}]'::jsonb, false, 7),
  ('edificio-cantaria', 'Edifício Cantaria', 'Comercial', 2020, 'Belo Horizonte, MG', 5200, 'Cantaria Incorporações', 'Um edifício de uso misto com térreo aberto à cidade.', array['O Edifício Cantaria reúne lojas no térreo, escritórios nos pavimentos intermediários e um terraço público na cobertura. O térreo recuado cria uma pequena praça coberta que devolve área à calçada.', 'A fachada em painéis de pedra natural, dispostos em ritmo irregular, faz referência às técnicas de cantaria e dá ao edifício uma presença sóbria na paisagem urbana.']::text[], '{"src":"https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=2000&q=80","alt":"Fachada do Edifício Cantaria","orientation":"portrait"}'::jsonb, '[{"src":"https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=2000&q=80","alt":"Vista do edifício a partir da rua","orientation":"portrait","caption":"Vista da esquina"},{"src":"https://images.unsplash.com/photo-1559329007-40df8a9345d8?auto=format&fit=crop&w=2000&q=80","alt":"Café no térreo do edifício","orientation":"landscape","caption":"Térreo comercial"},{"src":"https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=2000&q=80","alt":"Escritório nos pavimentos intermediários","orientation":"landscape","caption":"Pavimento corporativo"}]'::jsonb, false, 8);

insert into public.posts (slug, title, excerpt, category, published_on, reading_time, author, cover, body) values
  ('o-silencio-do-concreto', 'O silêncio do concreto', 'Por que continuamos a escolher o concreto aparente, e como ele pode ser um material delicado quando tratado com cuidado.', 'Materiais', '2026-08-18', 6, 'Helena Valadares', '{"src":"https://images.unsplash.com/photo-1486718448742-163732cd1544?auto=format&fit=crop&w=2000&q=80","alt":"Superfície de concreto aparente com luz rasante","orientation":"landscape"}'::jsonb, '[{"paragraphs":["Poucos materiais carregam tantos preconceitos quanto o concreto. Frio, pesado, brutal. Ainda assim, quando visitamos as obras que mais nos emocionam, é quase sempre ele que está ali, recebendo a luz de um jeito que nenhum outro material consegue.","No estúdio, tratamos o concreto como uma superfície que registra. Ele guarda a marca das fôrmas, o veio da madeira, o gesto de quem o moldou. É um material que conta como foi feito."]},{"heading":"A fôrma como desenho","paragraphs":["Grande parte do trabalho acontece antes da concretagem. Desenhamos a paginação das fôrmas com o mesmo cuidado com que desenhamos uma fachada, porque é ela que vai definir o ritmo das juntas e a textura final.","Tábuas de pinus estreitas deixam uma superfície mais vibrante. Compensados plastificados resultam em planos lisos, quase aveludados. Cada escolha muda a forma como a luz desliza pela parede ao longo do dia."],"quote":"O concreto não precisa de revestimento. Precisa de tempo e de luz."},{"heading":"Envelhecer bem","paragraphs":["Um material honesto envelhece com dignidade. O concreto aparente ganha manchas, pátina e pequenas imperfeições que, em vez de degradar, dão profundidade à superfície.","Talvez seja essa a razão pela qual voltamos sempre a ele: é um material que aceita o tempo, e arquitetura que aceita o tempo tende a permanecer."]}]'::jsonb),
  ('desenhar-com-a-luz', 'Desenhar com a luz', 'Notas sobre aberturas, sombras e a importância de observar um terreno em horários diferentes antes de desenhar qualquer linha.', 'Processo', '2026-07-02', 5, 'Marina Costa', '{"src":"https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=2000&q=80","alt":"Interior em tons claros com luz natural lateral","orientation":"landscape"}'::jsonb, '[{"paragraphs":["Antes de abrir o computador, passamos um dia inteiro no terreno. Chegamos cedo, voltamos no fim da tarde. Observamos por onde o sol nasce, onde a sombra das árvores cai ao meio-dia, como o vento se comporta.","Essas observações se transformam em decisões simples: onde abrir uma janela alta, onde recuar uma varanda, onde a parede deve ser cega para proteger o interior do calor."]},{"heading":"A luz como material","paragraphs":["Tratamos a luz como um material de projeto. Ela tem cor, temperatura e direção, e muda completamente a percepção de um mesmo espaço ao longo das horas."],"quote":"Um cômodo bem iluminado não é o mais claro. É aquele em que a luz chega no momento certo."}]'::jsonb),
  ('o-patio-como-centro', 'O pátio como centro da casa', 'Uma tipologia antiga que resolve problemas contemporâneos: privacidade, ventilação e contato diário com a natureza.', 'Ensaio', '2026-05-21', 7, 'Rafael Mendes', '{"src":"https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=2000&q=80","alt":"Casa contemporânea com pátio ao entardecer","orientation":"landscape"}'::jsonb, '[{"paragraphs":["Das casas romanas aos claustros, dos riads marroquinos às casas bandeiristas, o pátio sempre foi uma forma de trazer o céu para dentro de casa.","Em lotes urbanos cada vez mais estreitos, ele volta a fazer sentido. Voltar a casa para dentro permite abrir generosamente cada cômodo sem abrir mão da privacidade."]},{"heading":"Ventilação e conforto","paragraphs":["O pátio funciona como um pulmão. O ar quente sobe e sai pela abertura, enquanto o ar mais fresco entra pelas janelas opostas, criando uma ventilação cruzada constante e silenciosa."]}]'::jsonb),
  ('materiais-que-envelhecem-bem', 'Materiais que envelhecem bem', 'Uma pequena seleção de materiais que usamos com frequência e o que aprendemos com cada um deles ao longo dos anos.', 'Materiais', '2026-03-10', 4, 'Tomás Ribeiro', '{"src":"https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=2000&q=80","alt":"Mesa de trabalho com desenhos técnicos de arquitetura","orientation":"landscape"}'::jsonb, '[{"paragraphs":["Madeira maciça, pedra natural, cal, latão, terracota. São materiais que não pedem manutenção constante e que ficam mais bonitos com o uso.","A escolha de um material é também uma escolha sobre o futuro do edifício. Preferimos superfícies que aceitam marcas a acabamentos que precisam parecer novos para sempre."]}]'::jsonb),
  ('jardins-nativos', 'Jardins nativos, jardins possíveis', 'Como o paisagismo com espécies nativas reduz manutenção, atrai fauna e cria uma relação mais honesta com o lugar.', 'Paisagismo', '2026-01-28', 5, 'Luiza Andrade', '{"src":"https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=2000&q=80","alt":"Jardim com vegetação densa e luz filtrada","orientation":"landscape"}'::jsonb, '[{"paragraphs":["Um jardim de espécies nativas pede menos água, menos adubo e menos intervenção. Em troca, oferece sombra, abrigo para pássaros e uma paisagem que muda com as estações.","Começamos sempre por perguntar o que já cresce naturalmente na região. A resposta costuma ser mais rica e mais bonita do que qualquer catálogo de viveiro."],"quote":"O melhor jardim é aquele que parece ter estado sempre ali."}]'::jsonb),
  ('reformar-sem-apagar', 'Reformar sem apagar', 'Sobre o prazer de trabalhar em edifícios existentes e a responsabilidade de decidir o que deve permanecer.', 'Processo', '2025-11-14', 6, 'Bruno Farias', '{"src":"https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=2000&q=80","alt":"Estrutura de obra em andamento","orientation":"landscape"}'::jsonb, '[{"paragraphs":["Toda reforma começa com um inventário. Antes de qualquer demolição, fotografamos, medimos e catalogamos o que existe: pisos, esquadrias, ferragens, revestimentos.","Muitas vezes o melhor projeto é o que retira. Remover forros, divisórias e acréscimos revela a clareza original de um espaço que estava escondida havia décadas."]}]'::jsonb);

insert into public.services (slug, title, lead, description, deliverables, sort_order) values
  ('projeto-arquitetonico', 'Projeto Arquitetônico', 'Do estudo de implantação ao detalhamento executivo.', 'Desenvolvemos o projeto completo de residências, edifícios comerciais e equipamentos culturais. Cada proposta começa pela leitura do lugar, do clima e do modo de vida de quem vai habitar o espaço, e segue até o último detalhe construtivo.', array['Estudo preliminar', 'Anteprojeto', 'Projeto legal', 'Projeto executivo', 'Compatibilização']::text[], 1),
  ('interiores', 'Interiores', 'Espaços internos pensados como extensão da arquitetura.', 'Projetamos interiores com a mesma precisão da obra: materiais, luz, marcenaria e mobiliário sob medida. Trabalhamos com uma rede de artesãos e fornecedores que compartilham nosso cuidado com o acabamento.', array['Layout e fluxos', 'Marcenaria sob medida', 'Especificação de materiais', 'Curadoria de mobiliário', 'Iluminação']::text[], 2),
  ('consultoria', 'Consultoria', 'Um olhar técnico antes das decisões importantes.', 'Apoiamos clientes na escolha de terrenos, análise de viabilidade, revisão de projetos de terceiros e definição de programa. Uma conversa bem conduzida no início evita custos e frustrações ao longo da obra.', array['Análise de terreno', 'Estudo de viabilidade', 'Revisão de projeto', 'Definição de programa']::text[], 3),
  ('reforma', 'Reforma', 'Revelar o que já existe antes de acrescentar.', 'Em reformas e retrofits, começamos por entender a história do edifício. Preservamos o que tem valor, removemos o excesso e inserimos o novo de forma clara e respeitosa, com acompanhamento próximo da obra.', array['Levantamento cadastral', 'Diagnóstico', 'Projeto de reforma', 'Acompanhamento de obra']::text[], 4),
  ('paisagismo', 'Paisagismo', 'Jardins que amadurecem junto com a arquitetura.', 'Desenhamos jardins, pátios e áreas externas com espécies nativas e adaptadas ao clima, pensando na manutenção, na sombra e na passagem das estações. O paisagismo nasce junto com o projeto, nunca depois dele.', array['Plano de massas', 'Seleção de espécies', 'Projeto de irrigação', 'Detalhamento de pisos e muros']::text[], 5);

insert into public.team_members (name, role, photo_url, bio, sort_order) values
  ('Helena Valadares', 'Sócia fundadora', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80', 'Arquiteta pela FAU USP, conduz os projetos residenciais e culturais do estúdio.', 1),
  ('Rafael Mendes', 'Sócio fundador', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80', 'Coordena projetos corporativos e a relação com as equipes de obra.', 2),
  ('Marina Costa', 'Diretora de interiores', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=900&q=80', 'Responsável por interiores, marcenaria e curadoria de mobiliário.', 3),
  ('Tomás Ribeiro', 'Arquiteto associado', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80', 'Especialista em detalhamento executivo e sistemas construtivos.', 4),
  ('Luiza Andrade', 'Paisagista', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=900&q=80', 'Desenha jardins e áreas externas com espécies nativas.', 5),
  ('Bruno Farias', 'Arquiteto', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=900&q=80', 'Atua em reformas e retrofits de edifícios modernistas.', 6);

insert into public.awards (year, title, project, sort_order) values
  (2025, 'Prêmio IAB de Arquitetura', 'Casa do Vale', 1),
  (2024, 'Bienal Internacional de Arquitetura', 'Galeria Norte', 2),
  (2024, 'Design Awards Interiores', 'Atelier Lumen', 3),
  (2023, 'Prêmio Arquitetura Corporativa', 'Sede Terra', 4),
  (2022, 'Casa Brasileira, menção honrosa', 'Casa Pátio', 5),
  (2021, 'Prêmio Paisagem e Território', 'Pavilhão das Águas', 6);

insert into public.clients (name, kind, sort_order) values
  ('Instituto Norte de Arte', 'client', 1),
  ('Terra Engenharia', 'client', 2),
  ('Lumen Design', 'client', 3),
  ('Fundação Águas Claras', 'client', 4),
  ('Cantaria Incorporações', 'client', 5),
  ('Grupo Mirante', 'client', 6),
  ('Casa Bossa Hotéis', 'client', 7),
  ('Editora Linha', 'client', 8),
  ('Monolito', 'publication', 1),
  ('ArchDaily', 'publication', 2),
  ('Casa Vogue', 'publication', 3),
  ('Projeto', 'publication', 4),
  ('Wallpaper', 'publication', 5);

commit;
